# Generated by Django 4.1.5 on 2023-01-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_task_options_remove_task_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='nomer',
            field=models.CharField(default=1, max_length=10, verbose_name='Номер'),
            preserve_default=False,
        ),
    ]
